BASELINE = {
    'productionCapacity': 4000,
    'standardLeadTimeDays': 22,
    'maxOvertimeHoursPerDay': 4,
    'overtimeCostPerHour': 45,
    'workingDaysPerWeek': 5,
    'baseCostPerUnit': 8.50,
    'marginFloor': 0.15,
    'targetMargin': 0.22,
    'rushSurchargeRate': 0.12,
    'groundCostPerUnit': 0.30,
    'groundShippingDays': 5,
    'expressCostPerUnit': 0.85,
    'expressShippingDays': 3,
    'airCostPerUnit': 2.10,
    'airShippingDays': 1,
    'primarySupplier': 'ChemCorp Asia',
    'primaryLeadTimeDays': 10,
    'materialCostPerUnit': 3.20,
    'alternateSupplier': 'EuroChem GmbH',
    'alternateLeadTimeDays': 14,
    'alternateMaterialCostPerUnit': 3.80,
    'customerTier': 'Strategic',
    'relationshipYears': 5,
    'annualVolume': 120000,
    'acceptableDeliveryBuffer': 2,
}
